name: Test
on:
  push:
jobs:
  # jest-tests:
  #   name: Jest-Tests
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 15

  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Installing Dependicies in Server
  #       run: |
  #         cd server
  #         npm install
  #     - name: Running Tests
  #       run: |
  #         cd server
  #         npm test

  playwright-tests:
    name: Playwright-Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: mcr.microsoft.com/playwright:v1.28.0-focal
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
      # - name: Start Backend IT DIDNT WORK
      #   run: |
      #     cd server
      #     npm ci
      #     npm run start:dev &
      #     sleep 5
      - name: Install dependencies
        run: |
          cd client
          npm ci
          npm run build
          npx playwright install --with-deps
      # - name: Start frontend IT DIDNT WORK
      #   run: |
      #     cd client
      #     npm run dev &
      #     sleep 5
      - name: Run your tests
        run: |
          cd client
          npx playwright test

#   #to be done after
#   k6tests:
#     name: K6-Tests
#     timeout-minutes: 15
#     runs-on: ubuntu-latest
#     timeout-minutes: 15
#     steps:
#       - uses: actions/checkout@v2
